---

- name: Configure with Ansible
  hosts: all
  vars:
    ansible_user: 'vagrant'
    ansible_password: 'vagrant'

  # connection: local
  # gather_facts: false

  # pre_tasks:
  #   - debug: var=ansible_version

  tasks:
    - name: Print ansible facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print OS type
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Install dev tools
      win_chocolatey:
        name: 
        - git
        - vscode
        state: present

    - name: Install browsers
      win_chocolatey:
        name: 
        - googlechrome
        - firefox
        - brave
        state: present

    # Admin installations (note: become is not necessary b/c vagrant is admin)
    - name: Install Windows Terminal & PowerShell Core
      win_chocolatey:
        name: 
        - microsoft-windows-terminal
        - powershell-core
        - sysinternals
        state: present